---
- name: Set default editor
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/{{ shell_init_file }}"
    regexp: "export EDITOR={{ default_editor }}"
    line: "export EDITOR={{ default_editor }}"
